server:
  port: 8888

service:
  currency:
    uri: http://localhost:8090
    path:
      all-exchange: /all-exchange
      convert: /convert
    audience: currency-service
  stock:
    uri: http://localhost:8010
    path:
      stock-quotes: /get-stock-quotes
    audience: stock-service

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 6GIpCgc2IdAiWUFPdmT79WE5KRvpC4S9
            client-secret: vQIH1zhfbFLCbCXTAofV8VWvQLx9Gf2quTTnUoK4YZ3-cwkDogVwlGackhaxY-OZ
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-dnqy-t57.eu.auth0.com/